[context.development]
base = "/"
publish = "dist/"
command = "npm install && npm run build:dev"

[context.qa]
base = "/"
publish = "dist/"
command = "npm install && npm run build:qa"

[context.production]
base = "/"
publish = "dist/"
command = "npm install && npm run build:prod"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200